### ISSUE TITLE
Nested namespaces with mixed string/regex declarations create bad routes

### ISSUE THREAD

**Issue by smith186** [sinatra/sinatra-contrib#102]
Ran into this when upgrading from sinatra 1.3.5 to 1.4.2, with sinatra-contrib upgrading from 1.3.2 to 1.4.0. Here's an example of the issue:

```
namespace '/api/v1/items' do
	namespace %r{/(\d+)} do #:id
		before do
			@item = Item.find(params[:captures][0].to_i)
		end

		namespace '/children' do
			get '' do
				# This will never be found
			end
		end
	end
end
```

It looks like the concatenation of the routes generates the following regex:
```
(?-mix:^(?-mix:(?-mix:\/api\/v1\/items\z)(?-mix:(?-mix:\/(\d+))(?-mix:\/children\z)))$)
```
All of the namespaces defined as static strings get \z appended to them, which causes matches to fail.

As a workaround, I swapped out all of the static declarations for regexes (ex: %r{/children} instead of '/children') and it's working properly.

**Comment by zzak** [comment]
I think we should start with a failing test and go from there.

**Comment by zzak** [comment]
Please give this a try now that mustermann is merged and Sinatra::Namespace is using it! <3
