### ISSUE TITLE
make backports an optional dependency

### ISSUE THREAD

**Issue by trevor** [sinatra/sinatra-contrib#105]
Would it be possible to remove the backports dependency when it's not needed? This would simplify tracing errors and other possible backports related issues.

**Comment by speedmax** [comment]
What about a optional external dependencies that users can opt-in, loading hundreds of files slow down boot time in my app by 0.6s and mega bytes in memory.

```
# gem 'backports'  # uncomment this line if you are using older rubies < v2.0
gem "sinatra-contrib"
```

Is this tax worth the extra memory consumption and load time?

**Comment by zzak** [comment]
Closing as discussed on #133, thanks for your suggestion!
