### ISSUE TITLE
sinatra namespace vs rake namespace

### ISSUE THREAD

**Issue by roolo** [sinatra/sinatra-contrib#111]
Hi,
i am writing Sinatra API and it looks like namespace from sinatra-contrib interfere with rake namespaces (tasks behave like without namespace).

Is there some fix or workaround?

**Comment by zzak** [comment]
Closing since there is an available workaround in https://github.com/sinatra/sinatra-contrib/issues/111#issuecomment-43099374

If anyone can suggest a better solution, please submit a patch! <3

**Comment by dueckes** [comment]
The workaround proposed intends to prevent `sinatra-contrib` from loading when evaluating `rake` tasks.

Should you need both `sinatra-contib` and `rake` to co-exist, this solved it for me:

``` ruby
self.instance_eval do
  alias :namespace_pre_sinatra :namespace if self.respond_to?(:namespace, true)
end

require 'sinatra/namespace'

self.instance_eval do
  alias :namespace :namespace_pre_sinatra if self.respond_to?(:namespace_pre_sinatra, true)
end
```

**Comment by c-jones** [comment]
@dueckes where are you putting namespace alias code in your comment? The workaround for require false for the contrib gem is not working for me.

With the gem file set with the follow entry for sinatra-contrib:
`gem 'sinatra-contrib', :require => false`
I still see the owner of _namespace_ as _Sinatra::Delegator_ within my Rakefile and subsequently the error: 
`NoMethodError: undefined method 'task' for Sinatra::Application:Class`

**Comment by dueckes** [comment]
@c-jones In my case, I reverted to the standard `gem` declaration and when requiring 'sinatra/namespace' applied the workaround I offered above.
