### ISSUE TITLE
Sinatra::Reloader doesn't work when development? == false

### ISSUE THREAD

**Issue by nyantani** [sinatra/sinatra-contrib#114]
Sinatra::Reloader doesn't work when development? returns false.
https://github.com/sinatra/sinatra-contrib/blob/master/lib/sinatra/reloader.rb#L202

I suppose it's better to be written in [document](http://www.sinatrarb.com/contrib/reloader.html) as follows
  Override development? method when using Sinatra::Reloader.
or,
  Sinatra::Reloader only works when environment is equal to :development

**Comment by zzak** [comment]
As mentioned on #165 we will be deprecating the Reloader gem.

Thank you!
