### ISSUE TITLE
content_for not working in partials called from layout.haml

### ISSUE THREAD

**Issue by ebfg** [sinatra/sinatra-contrib#135]
My layout file looks like this:
`````
!!! 5
%html
  %head
    != yield_content :head
  %body
    != haml :'_navbar'
    != yield
`````

_navbar.haml looks like this:
`````
- content_for :head do
  :javascript
    // _navbar head
`````

Two other views called from yield also have `content_for :head` blocks that are rendered properly, however the navbar content is not rendered.

I did some digging and found that the navbar haml file is rendered after the `yield` call. I monkey patched `content_for` and `yield_content`:

`````
module Sinatra
  module ContentFor
    def content_for(key, &block)
      puts "adding content for #{key}"
      content_blocks[key.to_sym] << capture_later(&block)
    end
    def yield_content(key, *args)
      puts "yielding content for #{key}, blocks: #{content_blocks[key.to_sym].size}"
      content_blocks[key.to_sym].map { |b| capture(*args, &b) }.join
    end
  end
end
`````

Result:
`````
adding content for head
adding content for head
yielding content for head, blocks: 2
adding content for head
`````

How can I make it so the navbar partial is called before the yield?

**Comment by zzak** [comment]
As @jeremyevans suggested, there is an available workaround for this so I'm going to give this ticket a close.

Thanks for your report!
