### ISSUE TITLE
yield_content doesn't work with nested templates

### ISSUE THREAD

**Issue by thesmart** [sinatra/sinatra-contrib#140]
I've noticed a bug where calls to ```content_for``` from within nested templates do not work above the yield statement. I believe this undermines the usefulness of both features and isn't what is expected.  To illustrate the bug,  have created a repo:

https://github.com/thesmart/sinatra-template-bug

The main ```app.rb```:

```
require 'sinatra'
require 'sinatra/content_for'

get '/' do
  erb :body, :layout => :layout do
    erb :foobar
  end
end
```

and then ```layout.erb```:

```
<html>
  <head>
    <title>Test</title>
  </head>
  <body>
    layout
    <%= yield %>
  </body>
</html>
```

then ```body.erb```:

```
body
<%= yield_content :one %>
<%= yield %>
<%= yield_content :two %>
```

and finally ```foobar.erb```:

```
<% content_for :one do %>
  <script>
    alert('one');
  </script>
<% end %>
<% content_for :two do %>
  <script>
    alert('two');
  </script>
<% end %>
foobar
```

The output correctly shows

```
layout body foobar
```

but the only alert is "two".

**Comment by zzak** [comment]
:+1: For a documentation patch to explain this "feature"

/cc #135
