### ISSUE TITLE
Namespace loses inherited layout setting?

### ISSUE THREAD

**Issue by jng5** [sinatra/sinatra-contrib#142]
I have a modular app setup with a base Controller like this:

```ruby
module Controllers
  class Base < Sinatra::Application

    configure do
      set :root, File.expand_path('../../../', __FILE__)
      set :views, settings.root + '/app/views'
      set :erb, layout: :'layouts/layout'
    end

  end
end
```

Then I have a controller which inherits from that base controller:

```ruby
module Controllers
  class Content < Base
    namespace '/foo' do

      # this has no layout
      get '/bar' do
        erb :'content/bar'
      end

      # this works if we force the layout
      get '/bar' do
        erb :'content/bar', layout: :'layouts/layout'
      end

    end
  end
end
```

Am I doing something wrong? If I remove namespace, my layout setting is properly inherited.

For now, I'm just going to avoid using name spacing and add the prefix manually to my routes. Seems more sensible than specifying layouts for each route.

Thanks

**Comment by zzak** [comment]
This should be fixed in master by #139, thank you!
