### ISSUE TITLE
Sinatra::ConfigFile writes to stderr

### ISSUE THREAD

**Issue by mkaito** [sinatra/sinatra-contrib#144]
The only thing it does is pad your log files and be slightly annoying. I propose removing the [relevant line](https://github.com/sinatra/sinatra-contrib/blob/master/lib/sinatra/config_file.rb#L130), or using a logger instead of writing directly to stderr.

**Comment by zzak** [comment]
@mkaito Thanks for your suggestion!

Would you interested in writing a patch for this?

**Comment by mkaito** [comment]
Would removing the line be okay?

**Comment by zzak** [comment]
How about setting it to only during DEBUG?

**Comment by mkaito** [comment]
I've added it to my todo list. Will look at it when I next have some time.
