### ISSUE TITLE
content_for recursive array join error, rspec fails with slim

### ISSUE THREAD

**Issue by penguinstampede** [sinatra/sinatra-contrib#145]
after updating my bundle, I am running into this error:

ArgumentError at /
recursive array join

When running rspec on sinatra-contrib, there are 40 failures and all relate to slim...  most of the failures are in content_for.

rspec ./spec/content_for_spec.rb:179 # Sinatra::ContentFor Erb with yield_content in Slim renders blocks declared with the same key you use when rendering

also, the bundle, fwiw:

Using rake 10.3.2
Using backports 3.6.3
Using diff-lcs 1.2.5
Using erubis 2.7.0
Using tilt 1.4.1
Using haml 4.0.5
Using multi_json 1.10.1
Using rack 1.5.2
Using rack-protection 1.5.3
Using rack-test 0.6.2
Using rspec-core 2.99.2
Using rspec-expectations 2.99.2
Using rspec-mocks 2.99.2
Using rspec 2.99.0
Using sinatra 1.4.5 from git://github.com/sinatra/sinatra.git (at master)
Using sinatra-contrib 1.4.2 from source at .
Using temple 0.6.9
Using slim 2.0.2
Using yajl-ruby 1.2.1
Using bundler 1.6.0

**Comment by penguinstampede** [comment]
Decisions!  Need to move past Temple 0.6.8 if I want to use the Slim includes plugin.  But, still getting the "recursive array join" error using content_for with Temple 0.7.5.

Does that make this a Temple issue or a Sinatra-Contrib issue?

**Comment by minad** [comment]
See https://github.com/judofyr/temple/pull/86
