### ISSUE TITLE
respond_with doesn't work for MIME types with parameters

### ISSUE THREAD

**Issue by bk2204** [sinatra/sinatra-contrib#149]
I have a service that provides either Atom or RSS 1.0.  My service looks a bit like this (simplified):
```ruby
configure do
  mime_type :atom, 'application/atom+xml'
  mime_type :rss10, 'application/rss+xml; version="http://purl.org/rss/1.0/"'
end

get '/comics/:name/atom', :provides => [:atom] do
  respond_with :feed, comic: comics.comic(name)
end

get '/comics/:name/feed', :provides => [:atom, :rss10] do
  respond_with :feed, comic: comics.comic(name)
end

get '/comics/:name/rss10', :provides => [:rss10] do
  respond_with :feed, comic: comics.comic(name)
end
```

Accessing `/comics/:name/rss10` via curl never works, even without an Accept header, nor does `/comics/:name/feed` with `application/rss+xml`. I get a 406 Not Acceptable or a 404 Not Found. If I remove the parameter from the `mime_type` definition, it works fine. I definitely want to provide the version header to let tools know that this is RSS 1.0, not RSS 2.0, but it doesn't seem to work with `respond_with`.

**Comment by zzak** [comment]
@bk2204 Hello! Thank you for your suggestion!

I think this is an Accept-able feature :trollface: but would need a patch.
