### ISSUE TITLE
namespace with modular apps

### ISSUE THREAD

**Issue by Thermatix** [sinatra/sinatra-contrib#150]
I'm posting this here as I can't find anything on this and my attempt to get information from stack was unsuccessful. Does the namespace module simply not work when you're using module style apps?

i.e. like this:
```
module Sinatra
  module App
    module Test
      self.registered(app)
        namespace '/api' do
        end
      end
    end
  end
end


class App < Sinatra::Base
  register Sinatra::App:Test
end

```

because All I get is 'namespace is undefined' errors.

p.s. unrelated question but just wanting to know, do I need to put any of my route modules under the Sinatra Namespace? I mean I am but I'm just curios if It's necessary.

**Comment by Thermatix** [comment]
Ok, I think I understand it now, you can't use namespace within modular style apps that have the routes within a module (ie. `app.get '/some/route' do 'hey' end`); it has to be within the class inherited style.

**Comment by dkobia** [comment]
On the contrary, you can use namespace within modular apps, and using your example:

```
module Sinatra
  module App
    module Test
      self.registered(app)
        app.namespace '/api' do
          get '/users' do
            # do something
          end
        end
      end
    end
  end
end
```

**Comment by Thermatix** [comment]
Does does that mean anything that would normally be by itself like `namespace` work like this as well? 
I.e. For  the json  module you would do

```ruby
  app.json :foo => 'bar'
```

instead of

```ruby
   json :foo => 'bar'
```

**Comment by zzak** [comment]
@Thermatix yes, exactly. You must use the `app` instance in this case (when inside the `registered(app)` block)
