### ISSUE TITLE
Sinatra 1.4 requires a different version of Tilt than what sinatra-contrib requires

### ISSUE THREAD

**Issue by gffuentes** [sinatra/sinatra-contrib#153]
Unable to activate sinatra-contrib-1.4.2, because tilt-2.0.1 conflicts with tilt (~> 1.3) (Gem::ConflictError)

  In Gemfile:
    sinatra-contrib (>= 0) ruby depends on
      tilt (~> 1.3) ruby

    sinatra (~> 1.4) ruby depends on
      tilt (2.0.1)

**Comment by boblmartens** [comment]
Just ran into this today as well.

**Comment by gffuentes** [comment]
@boblmartens - i was able to get around this. If i recall, i uninstalled all versions of tilt and sinatra conrtib then bundled (with contrib in my gemfile). That installed just fine!

**Comment by zzak** [comment]
9cd766a496cde59d661abaea6633613ecdc7806d

**Comment by boblmartens** [comment]
Thanks @zzak! I'm wondering if you know when an official release might be sent out.

**Comment by zzak** [comment]
When the build is green ;)

**Comment by boblmartens** [comment]
Touche. :-)

**Comment by rishav** [comment]
Is this fixed ? Any ideas what is the work around for this ?

**Comment by kdubbels** [comment]
Method described by @gffuentes worked perfectly for me. ```gem uninstall sintra-contrib``` and ```tilt```, add them to Gemfile and run ```bundle install```
