### ISSUE TITLE
content_for is printing a proc when template code is in the content_for block

### ISSUE THREAD

**Issue by burlesona** [sinatra/sinatra-contrib#156]
This is almost identical to the previously closed issue: https://github.com/sinatra/sinatra-contrib/issues/25

However, I do not have and have never had the old `sinatra-content-for` gem. My relevant gems:

```
    sinatra (1.4.6)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    sinatra-contrib (1.4.2)
      backports (>= 2.0)
      multi_json
      rack-protection
      rack-test
      sinatra (~> 1.4.0)
      tilt (~> 1.3)
    slim (3.0.3)
      temple (~> 0.7.3)
      tilt (>= 1.3.3, < 2.1)
```

If I have a yield like:
```
== yield_content(:footer)
```
...and a block like:
```
= content_for(:footer) do
  p Hello Footer
```
It does yield the paragraph to the footer, but it also prints a `proc.inspect` into the template where the `content_for` is called. You can't use `- content_for(...){...}` because it errors with `recursive array join`.

It seems like this is a known issue that has cropped up before, and therefore is possibly a regression caused by a patch at some point in time, but I haven't been able to figure it out. Anyone have any insight on this?

**Comment by ijin82** [comment]
confirm. have the same problem. sad, sad story.
sinatra (1.4.6)
sinatra-contrib (1.4.2)
slim (3.0.3)
temple (0.7.5)

**Comment by minad** [comment]
See https://github.com/judofyr/temple/pull/86
