### ISSUE TITLE
Bump dependency for tilt

### ISSUE THREAD

**Issue by rmetzler** [sinatra/sinatra-contrib#157]
I ran into the following problem today:

This is my Gemfile
```ruby
source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
```

This is the error I get:
```
$ bundle
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Bundler could not find compatible versions for gem "tilt":
  In Gemfile:
    sinatra-contrib (>= 0) ruby depends on
      tilt (~> 1.3) ruby

    sinatra (>= 0) ruby depends on
      tilt (2.0.1)
```

It seems like the issue is actually fixed in https://github.com/sinatra/sinatra-contrib/commit/9cd766a496cde59d661abaea6633613ecdc7806d but no actual release was pushed.

**Comment by rmetzler** [comment]
see #153

**Comment by zzak** [comment]
We will ship a release soon, thanks for your patience.

**Comment by anthonator** [comment]
Any updates on when this will land?

**Comment by TrevorBramble** [comment]
@anthonator We're still trying to get a green build. If it's critical for you, maybe temporarily specify the commit sha in your Gemfile?

**Comment by anthonator** [comment]
I have a library that depends on this and I've got people asking. Really just looking for a timeframe.

**Comment by TrevorBramble** [comment]
Lies, damn lies, and software delivery estimates. ;^)

Can't even guess. You're welcome to watch for any progress in [the Slack room](https://sinatrarb.slack.com/messages/sinatra-contrib/), and jump in if you have any ideas! We're chasing down all of the transitive dependencies and environmental conditions we can identify but so far it's been fruitless.
