### ISSUE TITLE
unf_ext fails to build on ruby-head(2.3.0)

### ISSUE THREAD

**Issue by ashleygwilliams** [sinatra/sinatra-contrib#163]
error exists on travis and was able to replicate locally.
gist with error output and `mkmf.log` => https://gist.github.com/ashleygwilliams/97dc7eb34f43fdbf3952
filed issue here: https://github.com/knu/ruby-unf_ext/issues/12

**Comment by zzak** [comment]
Fixed in ruby trunk by https://github.com/ruby/ruby/commit/356baf95db7162b5a964dd17a8fe871afe805cf5
