### ISSUE TITLE
review HTTP status codes, tests, for respond_with

### ISSUE THREAD

**Issue by ashleygwilliams** [sinatra/sinatra-contrib#164]
related: #147 

currently the only status code we deliberately set is `406`. this occurs in one place in the code, here:
https://github.com/sinatra/sinatra-contrib/blob/master/lib/sinatra/respond_with.rb#L120

we have 3 tests for this:

A. https://github.com/sinatra/sinatra-contrib/blob/master/spec/respond_with_spec.rb#L95-L99
```ruby
it 'does not set up default handlers' do
      respond_to
      req.should_not be_ok
      status.should == 406
end
```
B. https://github.com/sinatra/sinatra-contrib/blob/master/spec/respond_with_spec.rb#L184-L188
```ruby      
it 'results in a 406 if format cannot be produced' do
     respond_with({})
     req(:html).should_not be_ok
     status.should == 406
end
```
C. https://github.com/sinatra/sinatra-contrib/blob/master/spec/respond_with_spec.rb#L204-L209
```ruby
it 'does not use name.engine for engines producing other formats' do
     respond_with :not_html
     req(:html).should_not be_ok
     status.should == 406
     body.should be_empty
end
```

we are now (with #147) considering adding, D:
```ruby
it 'results in a 404 if no template is found' do
     data = { :au => 'revoir' }
     respond_with :idontexist, data
     req.should_not be_ok
     status.should == 404
end
```

Some questions:
- Should A be a `404` not a `406`? I believe A should be the same as the D, and I think we have good reason to believe that D should `404`.
- Should we be checking that the body is empty, like C, for every test? (Consistency is good)
- When we finally decided to do an exception for D, should we add exceptions for all of these?

**Comment by zzak** [comment]
Ahhh, I missed this one.. sorry!

**Comment by docwhat** [comment]
Shouldn't A, B and C be 406 and D be a 500?

After all, the client requests MIME type(s) in the `Accepts:` header and the server cannot serve it in any of those formats.

* In A there are no possible response formats.
* In B there are no possible response formats.
* In C the client requests a format that isn't available.
* In D the client requests a format and then can't find the template, which is an application error (internal) error that the client cannot do anything about.

I can see using exceptions to allow someone to override this behavior (like always returning html or text if no possible response matches) but that probably shouldn't be the default behavior.

**Comment by zzak** [comment]
I changed this in /fe860ecbbfdb38da39d01b2b3ffc081e20e4eb8f to always 500 with "Unknown template engine" message. From there, people can catch the 500 and do what they want.

Probably 500 is less confusing than 406 or 404, since the problem is actually missing file from the application -- not that the user did anything wrong IMO.
