### ISSUE TITLE
Sinatra Reloader doesn't work well with modules

### ISSUE THREAD

**Issue by gipnokote** [sinatra/sinatra-contrib#165]
When you have a Sinatra application with modules, Reloader works fine only when the "main" file is changed. When the file that contains the module is changed, it results in 404.

Let's say we have this simple application:

```ruby
require 'sinatra/base'
require 'sinatra/reloader'

class DevportalWeb < Sinatra::Base
  configure :development do
    register Sinatra::Reloader
    also_reload 'app/*.rb'
  end

  require 'talk'
  register Talk
end
```

and it's module Talk where we have a route:

```ruby
module Talk
  def self.registered(app)
    app.get '/say' do
      'hello'
    end
  end
end
```

We can access '/say' and see it working, we can change the code in the main file and see it working, but when we change the code in the module, we'll see 404.

As far as I understand, this happens because reloader simply requires the changed file, but in this case it's not enough: "register" has to happen after that and it doesn't.

If (as an experiment) we modify (hardcode) the gem code so that 'updated?' for the main file would always be true, and it would always be treated as changed, and always reloaded, then "register" would always happen, and app wouldn't break on module's code change.

This proves that the problem can be solved with a certain effort, but we need to know which file is actually "main".

I wasn't able to think of a nice way to make it work to propose a pull request. Maybe you can?

**Comment by zzak** [comment]
Hello!

As result of our discussion on #44 we will be working to deprecate the `Sinatra::Reloader`, so I'm going to close this ticket.

If anyone has any suggestions on how to improve the Reloader api, please submit a patch.

Thank you!!
