### ISSUE TITLE
sinatra/namespace drops ERB escaping option

### ISSUE THREAD

**Issue by pedro** [sinatra/sinatra-contrib#166]
Hey folks!

Kind of a follow up to #28 and #139: the setting to always escape html in ERB is not being applied inside a namespace.

For instance:

```ruby
class Myapp < Sinatra::Base
  register Sinatra::Namespace

  set :erb, escape_html: true

  get '/' do
    erb :test
  end

  namespace '/namespace' do
    get do
      erb :test
    end
  end
end
```

Given a simple view like:

```ruby
<%= "<b>Should be escaped</b>" %>
```

You can clearly see the different behavior (escaped output under `/`, unescaped under `/namespace`).

For the full reproduction check this gist:
https://gist.github.com/pedro/7983413e88ab93fa8764

**Comment by pedro** [comment]
Nevermind, fixed in master :}
Thanks!

**Comment by zzak** [comment]
Can confirm.
