### ISSUE TITLE
Provide better examples of namespace definition in classic and modular apps

### ISSUE THREAD

**Issue by TrevorBramble** [sinatra/sinatra-contrib#167]
I looked at the [namespace docs](http://www.sinatrarb.com/contrib/namespace.html) after today's comment on #150 and it looks like the real problem is that we don't give any clear examples of how to define namespaces.

**Comment by stjhimy** [comment]
I added regex and app examples on #195
Is it enough?

**Comment by zzak** [comment]
I think #195 and #194 definitely help!

Always welcome more docs, particularly after all the hard work to upgrade Namespace for Sinatra 2.0 ;) ;)
