### ISSUE TITLE
$KCODE is exposed for all Ruby versions, gives warning on Ruby v1.9 and up

### ISSUE THREAD

**Issue by thomax** [sinatra/sinatra-contrib#168]
As I understand it, versions of Ruby before 1.9.0 needed the $KCODE flag set to handle multibyte characters properly. It seems a bit harsh to give everyone on Ruby v1.9+ the below warning:

```
.rvm/gems/ruby-2.2.1/gems/sinatra-contrib-1.4.4/lib/sinatra/respond_with.rb:4: warning: variable $KCODE is no longer effective; ignored
```
Would it be a good idea to check the Ruby version in order to avoid the warning?

```ruby
$KCODE = 'UTF8' unless RUBY_VERSION > "1.9.0"
```

Or is there a better solution for getting rid of this warning which I haven't caught on to?

**Comment by ashleygwilliams** [comment]
ah yeah, that is something i did- didn't realize it was giving a warning. i'll fix it. your solution seems good to me!

**Comment by TrevorBramble** [comment]
Awesome. Thanks, @thomax and @ashleygwilliams!

**Comment by thomax** [comment]
Wow, you guys are fast! Thanks a lot!

**Comment by ashleygwilliams** [comment]
:rocket:
