### ISSUE TITLE
warning: variable $KCODE is no longer effective;

### ISSUE THREAD

**Issue by jonyt** [sinatra/sinatra-contrib#172]
I'm getting `/home/johnny/.rvm/gems/ruby-2.1.6/gems/sinatra-contrib-1.4.4/lib/sinatra/respond_with.rb:4: warning: variable $KCODE is no longer effective; ignored`. Simplest fix would be to delete that line. Unless you're keeping it for backwards compatibility?

**Comment by ashleygwilliams** [comment]
hey @jonyt - we are keeping it for backwards compatibility. what version of ruby are you using?

**Comment by ashleygwilliams** [comment]
oh i see. you are using 2.1.6. it should not give you a warning since my patch... https://github.com/sinatra/sinatra-contrib/commit/df916656c182cd361f5013e34c42ce04b6d3890f. don't think that has been released yet, but when we next release, it will be fixed. sorry about that!
