### ISSUE TITLE
'helpers' and 'before' not available for namespace with regex

### ISSUE THREAD

**Issue by Benjamin-Dobell** [sinatra/sinatra-contrib#176]
I have a namespace with regex:

```
namespace /provider\/([^\/&?]+)\/tag\/([^\/&?]+)/ do
```

I attempted to add some helpers (tried both module and block syntax), and also a ```before``` block. The ```before``` block does not execute, and the helper methods are not available.

simply replacing the above regex with params syntax:

```
namespace '/provider/:provider/tag/:provider_id' do
```

causes the ```before``` block to be executed and the helper methods to be available within routes.

Of course, this is a very simplistic regex, provided as an example. I have more complex regex that can't be replaced by params syntax.

**Comment by TrevorBramble** [comment]
@Benjamin-Dobell thanks for filing the issue. If you're interested, adding your failing case to the spec file would be a help!

**Comment by stjhimy** [comment]
You have to consider the `//` on the route when writing the regex, try this: 

`namespace /\/provider\/([^\/&?]+)\/tag\/([^\/&?]+)\// `

I have added missing specs for this on https://github.com/sinatra/sinatra-contrib/pull/194 using your example.

**Comment by Benjamin-Dobell** [comment]
Oh, wow, of course! I didn't even realise I'd missed them. Now I feel a bit stupid :wink:

Thanks!
