### ISSUE TITLE
Should Sinatra::Reloader reload i18n files (.yml)?

### ISSUE THREAD

**Issue by bmsatierf** [sinatra/sinatra-contrib#179]
The extension **Sinatra::Reloader** should reload other files such as `yml` with translations used by the gem **i18n**? Here is the setup:

```ruby
# Gemfile

gem 'i18n'
gem 'sinatra'
gem 'sinatra-contrib'
```

```ruby
# my_app.rb

require "sinatra/base"
require "sinatra/reloader"

class MyApp < Sinatra::Base
  configure :development do
    register Sinatra::Reloader
  end

  configure do
    I18n::Backend::Simple.send(:include, I18n::Backend::Fallbacks)
    I18n.load_path = Dir[File.join(settings.root, 'config/locales', '*.yml')]
    I18n.backend.load_translations
  end

  ...
end
```

```yml
# config/locales/pt.yml

pt:
  hello: "Olá Sinatra"
```

After changing the `pt.yml` file, the changes would be visible only after restarting the server.

**Comment by canton7** [comment]
Can't you use `also_reload` to include the `.yml` files, see http://www.sinatrarb.com/contrib/reloader.html#label-Changing+the+Reloading+Policy ?

**Comment by bmsatierf** [comment]
Hi @canton7, thank you for the suggestion.

Before opening this issue I tried to use `also_reload`, however I ended up with an error while trying to require an `.yml` file, and then I realised that perhaps only `.rb` would be reloaded, but I am still not sure.

**Comment by ireneybean** [comment]
I'm having the same experience, I tried using also_reload and it is fine starting up, but after changing the content in my yml file I get an error saying it can't load the file and the error message says it is looking in my home directory even though I have specified the path the same way as other also_reload files that are .rb.

**Comment by zzak** [comment]
I think because '.yml' files aren't technically `require`d but read from source?

It looks like, [from here](https://github.com/sinatra/sinatra-contrib/blob/c25e37b92822cbd3dc0870ce9c6cfdab47720c9d/lib/sinatra/reloader.rb#L234-L236), that the reloaded essentially just calls `require` on the file after removing the element from Sinatra and removing the file from `$LOADED_FEATURES`.

**Comment by stjhimy** [comment]
We could add a method `after_reload` that would accept a block allowing the user to call `I18n` to update yml files or run anything he needs after the reload. What do you think @zzak ?

**Comment by zzak** [comment]
@stjhimy Sounds good to me, will you work up a patch for `after_reload` feature as well as documentation regarding this behavior?

**Comment by stjhimy** [comment]
@zzak yes, I'm on it.
