### ISSUE TITLE
Namespace home routes

### ISSUE THREAD

**Issue by izwick-schachter** [sinatra/sinatra-contrib#188]
In namespaces when I create a namespace like so:

    namespace "/test" do
        get {erb :whatever}
    end

I would like both `/test/` and `/test` to go to the route I defined, the same way if I go to `website.com/` and `website.com` it goes to the same route (`/`). Why doesn't this happen? Is this by design or is this a bug?

**Comment by stjhimy** [comment]
This allows you to have a page in a level above, anything outside the `/namespace/` should not be handled by the namespace itself, if you want both `/foo` and `/foo/` to use the same route you could try: 

```ruby
get '/foo' do
  redirect '/foo/'
end

namespace '/foo' do
  get '/' do
    'bar'
  end
end
```

**Comment by zzak** [comment]
Yes, exactly.

As a side note, this is how Sinatra treats URLs.

Please see sinatra/sinatra#1107 for more discussion.
