### ISSUE TITLE
How to flush content_for?

### ISSUE THREAD

**Issue by GaryKing** [sinatra/sinatra-contrib#204]
How can I flush content_for, so that if I use it a partial view that is called several times, the symbol doesn't keep the content from the previous calls to that partial view?

**Comment by stjhimy** [comment]
Is it possible to provide some testable code to replicate? Thanks!

**Comment by GaryKing** [comment]
Basically I'd like to have the "flush" option that exists in [content_for in Rails](http://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-content_for).

**Comment by zzak** [comment]
There's currently no explicit "flush"-like feature in content_for.

If you want, you could re-assign key new content by using `clear_content_for` and then set `content_for` again. You would lose the previous content however, unless you set it to a different key first, like:

```ruby
content_for :something_else do
  yield_content :that_other_thing
end
```

But then you have to use `:something_else` entirely.

I wouldn't be apposed to adding the "flush" feature if you're interested in working on it!
