### ISSUE TITLE
content_for w/ slim

### ISSUE THREAD

**Issue by tkellen** [sinatra/sinatra-contrib#25]
I'm not sure if I should be posting this here or on the Slim repo, but content_for is broken using this templating engine.

**Test Case**

app.rb:

``` ruby
require 'slim'
require 'haml'
require 'sinatra/base'
require 'sinatra/content_for'

class Main < Sinatra::Base

  helpers Sinatra::ContentFor

  get '/' do
    slim :test
  end

end
```

views/layout.slim:

``` ruby
html
  head
    meta charset='utf8'
    title test
  body
    == yield
    == yield_content :test
```

views/test.slim

``` ruby
- content_for :test do
  test content

h1 page title

h2 page subtitle
```

... the block return isn't working correctly, it sends the entire template.  Using = content_for works, but since that returns a proc, it prints #[<Proc... on the page where you've defined the content block.

**Comment by burlesona** [comment]
I'm getting this exact same behavior (printing the proc where the content_for block is called) after updating to Sinatra 1.4.6. I've never installed the `sinatra-content-for` gem and am running via bundle exec. Any ideas?
