### ISSUE TITLE
Sinatra::Namespace does not prefix redirect() nor url()

### ISSUE THREAD

**Issue by metakeule** [sinatra/sinatra-contrib#27]
I would expect the redirects to be prefixed like the routes.

    namespace '/admin' do
        get '/a' do
            redirect '/b'  # is not redirecting to '/admin/b' but to '/b'
        end

        get '/a' do
            redirect to('/b')  # is not redirecting to '/admin/b' but to '/b'
        end
     end

:prefixed_redirects raises an error

    namespace '/admin' do
        enable :prefixed_redirects
        get '/somewhere'
     end

     # => may not set prefixed_redirects (ArgumentError)

I don't know where this should be fixed

    module Sinatra::Namespace::NamespacedMethods
        prefixed :to
    end

didn't help either.

**Comment by zzak** [comment]
This needs an (actual) failing test and patch before it can be fixed.

**Comment by stjhimy** [comment]
@zzak I added a method called "redirect_to" in the #180 that allows redirects within the namespace.

**Comment by zzak** [comment]
This can be closed by #180 which included specs for redirect in a namespace
