### ISSUE TITLE
Sinatra::Namespace doesn't respect some settings?

### ISSUE THREAD

**Issue by chanks** [sinatra/sinatra-contrib#28]
In my main configure block I use:

    set :haml, :format => :html5, :ugly => true

When I use the 'haml' helper to render a page for a normal (non-namespaced) route handler, it appears as I'd expect - with the HTML5 doctype and the ugly formatting. But when I use the 'haml' helper in a namespaced route handler, it appears that neither of these options are being respected.

I can work around this by doing haml :template, :format => :html5, :ugly => true in every namespaced route handler, which isn't exactly clean. I've tried using a set :haml line with the same options inside my namespace, but then I get a "may not set haml" error.

**Comment by ginjo** [comment]
This is still an issue in January 2015 with sinatra 1.4.5 and sinatra-contrib 1.4.2.
Is there a correct way to allow namespace access to application settings (and functionality that is dependent on application settings, like templates etc)?

If not, is there a future path of likely resolution, so we can at least structure our applications in a way that will accommodate the eventual solution?

**Comment by pedro** [comment]
Just ran into this too – sinatra 1.4.6, sinatra-contrib 1.4.2:

Here's a very simple way to reproduce, extending on @zzak's:

```
require 'sinatra'
require 'sinatra/namespace'

set :foo, 42

get "/test" do
  settings.respond_to?(:foo).to_s
end

namespace '/namespace' do
  get '/test' do
    settings.respond_to?(:foo).to_s
  end
end
```

The monkeypatch suggested by @reconbot worked for me:

```
module Sinatra
  module Namespace
    module InstanceMethods
      def settings
        super.settings
      end
    end
  end
end
```

I'd send a pull, but not aware of the context here and why `settings` is being defined this way in first place. Any takers?
