### ISSUE TITLE
Deprecate Sinatra::Reloader

### ISSUE THREAD

**Issue by TrevorBramble** [sinatra/sinatra-contrib#40]
See: http://travis-ci.org/#!/TrevorBramble/sinatra-contrib/jobs/852727

This appears to actually be a spec failure due to how we're writing and loading temporary app files for these specs; a simple example app with sinatra/reloader required don't fall over.

Failure output extract:
```
51  1) Sinatra::Reloader automatically registers the reloader in the subclasses
52     Failure/Error: get('/foo').body.should == 'bar'
53       expected: "bar"
54            got: "foo" (using ==)
55     # ./spec/reloader_spec.rb:438:in `__script__'
56     # kernel/common/eval19.rb:45:in `instance_eval'
57     # kernel/bootstrap/array19.rb:18:in `map'
58     # kernel/bootstrap/array19.rb:18:in `map'
```

**Comment by ashleygwilliams** [comment]
any further thought on this?

**Comment by zzak** [comment]
We could probably deprecate and remove the reloader, but not sure

**Comment by TrevorBramble** [comment]
@ashleygwilliams @zzak I'm game for deprecating and removing it. If the Sinatra-specific reloader doesn't give us any value over a more generic tool, I'd rather see it gone. If someone wants to adopt it as a stand-alone mod, great.

**Comment by zzak** [comment]
Also, since the spec is no longer failing, I'm not sure there's any good reason to remove it.

I guess the reloader works for most people? There haven't been any bugs filed against it in a while.

In that case, why remove a feature if it's not causing any harm.

**Comment by stjhimy** [comment]
Last time I checked #179 still an issue. 
I will run some tests tonight and get back to you. 
Is there any valid alternative to sinatra/reloader? Shotgun only? https://github.com/rtomayko/shotgun

**Comment by zzak** [comment]
After looking into that ticket, I'm not sure we could consider it a bug since it's out of the scope of the reloader. Although I'm not sure where it's explicitly written, based on the implementation, it's just calling `require`.

I'm not sure that's worth removing the feature all together.

**Comment by stjhimy** [comment]
Indeed, I did ran a few tests on the sinatra/reloader and it seems to be working fine. 
The `yml` issue goes as you said, it's not a rb file so it's not reloaded. 

We can close #40 and #196, if we decide to remove the reloader in the future then we can just merge #196.

**Comment by zzak** [comment]
We'll keep the reloader for now, it's not causing such a major burden and some people still find it useful.
