### ISSUE TITLE
sinatra-reloader doesn't play nicely with filters defined in multiple files

### ISSUE THREAD

**Issue by cespare** [sinatra/sinatra-contrib#48]
Sinatra runs filters in the order that they are defined. If you define your filters in multiple files, then typically you just need to make sure that they are required in the correct order and then you're golden. However, with sinatra-reloader, if you modify a file which defines a filter and it is reloaded, that filter will now be run at the end of the filters.

Concrete example: suppose you have `before` filters A and B defined in `a.rb` and `b.rb`, respectively. They assume that they are run in that order (A then B) and so `a.rb` is required before `b.rb`. If you modify `a.rb`, it will be reloaded and now when you make a request, B will be run before A.

Is there a known workaround for this or a good approach for mitigating this kind of problem in development?

**Comment by zzak** [comment]
As mentioned on #165 we will be deprecating the Reloader gem.

Thank you!
