### ISSUE TITLE
how to set cookies expires in Sinatra::Cookies

### ISSUE THREAD

**Issue by krhougs** [sinatra/sinatra-contrib#59]
how to set cookies expires in Sinatra::Cookies

**Comment by Hubro** [comment]
Was any syntactic sugar ever added for this?

**Comment by Hubro** [comment]
@yesmeck Where is that documented? It doesn't appear to be possible:

http://www.rubydoc.info/github/rack/rack/master/Rack%2FResponse%2FHelpers%3Aset_cookie

**Comment by yesmeck** [comment]
@Hubro Sorry. It's too long ago to member.
